name: ci
on:
  push:
    branches:
      - main
jobs:
  example:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup example
        run: |
          mkdir -p example/.fluentci
          cp -r src example/.fluentci
          cp Cargo.toml example/.fluentci
          cp Cargo.lock example/.fluentci
      - name: Setup Fluent CI CLI
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          plugin: .
          args: |
            setup zulu-17.46.19
          working-directory: example
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Show Java version
        run: |
          type java
          java -version
      - name: Change Java version
        run: |
          fluentci run --wasm . setup 21.0.2
          type java
          java -version
        working-directory: example
